install:
	install -m 644 77-usbserial-renumber.rules /etc/udev/rules.d/
	install usb_topology /usr/local/bin/

uninstall:
	rm -f /etc/udev/rules.d/77-usbserial-renumber.rules
	rm -f /usr/local/bin/usb_topology


