#!/usr/bin/python
# $ usb_topology /devices/pci0000:00/0000:00:1d.7/usb1/1-3/1-3.4/1-3.4.1/1-3.4.1:1.0/ttyUSB0/tty/ttyUSB0
# TOPOLOGY=port3port4port4
import sys, re

topo_pat = re.compile("^\d+-([\d\.]+):[\d\.]+$")

topology = None
for i in sys.argv[1].split("/"):
    m = topo_pat.match(i)
    if m:
        topology = "".join(["port%s" % x for x in m.group(1).split(".")])

if topology:
    print("TOPOLOGY=%s" % topology)

